# ------------------------------------------------------------
# Default Site
# ------------------------------------------------------------

server {
  listen 80 default;

  server_name default-host.localhost;
  access_log /data/logs/default-host_access.log combined;
  error_log /data/logs/default-host_error.log warn;

  root /var/www/html;

  include conf.d/include/letsencrypt-acme-challenge.conf;
  
  error_page 404 /error404.html;
  
  location = /error404.html {
    internal;
    access_log off;
  }
  
  location / {
    return 404;
  }

}
