# ------------------------------------------------------------
# Default Site
# ------------------------------------------------------------

server {
  listen 80 default;
  listen 443 ssl default;

  ssl_certificate     /etc/letsencrypt/live/npm-10/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-10/privkey.pem;

  server_name default-host.localhost;
  access_log /data/logs/default-host_access.log combined;
  error_log /data/logs/default-host_error.log warn;

  root /var/www/html;

  include conf.d/include/letsencrypt-acme-challenge.conf;

  error_page 401 /error401.html;
  error_page 403 /error403.html;
  error_page 404 /error404.html;
  error_page 408 /error408.html;
  error_page 429 /error429.html;
  error_page 500 /error500.html;
  error_page 502 /error502.html;
  error_page 503 /error503.html;

  location ~ ^/error[0-9]+\.html$ { internal; }

  location / {
    return 404;
  }

}
