# Pages d'erreur personnalisées (persistant via volume Docker)
error_page 401 /error401.html;
error_page 403 /error403.html;
error_page 404 /error404.html;
error_page 500 /error500.html;
error_page 502 /error502.html;
error_page 503 /error503.html;
